name: todolist
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_svg: ^2.0.16

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: SFPro-Bold
      fonts:
        - asset: assets/fonts/SFProText-Bold.ttf
    - family: SFPro-Regular
      fonts:
        - asset: assets/fonts/SFProText-Regular.ttf
